services:
  eureka-server:
    build:
      context: ./EurekaServer/EurekaServer
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka-server:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  config-server:
    build:
      context: ./configServer/configServer
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - my-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  gateway-server:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "9090:9090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - my-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server :
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway-server:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  my-network:
    driver: bridge